project: kicksware
component: search
nameOverride: search-service
fullnameOverride: search-service

replicaCount: 1
image:
  registry: registry.kicksware.com
  repository: api/search-service
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: api.kicksware.com
      paths:
        - /search
      middlewares: []
      services:
        - name: search-service
          port: 8080
          scheme: http
    - host: api.kicksware.com
      paths:
        - /health/search
      middlewares:
        - name: health-stripprefix
          namespace: gateway
      services:
        - name: search-service
          port: 8080
          scheme: http
    - host: rpc.kicksware.com
      grpc: true
      paths:
        - /proto.SearchReferencesService
        - /proto.SearchProductService
      entrypoints:
        - web
        - websecure
      services:
        - name: search-service
          port: 8080
          scheme: h2c

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  mounts:
    - name: auth-keys
      mountPath: /root/keys/auth
    - name: grpc-tls
      mountPath: /root/certs/grpc
    - name: mongo-tls
      mountPath: /root/certs/mongo

config:
  environment: PROD
  configMountPath: /root/env

environment:
  ENV: k8s
  CONFIG_PATH: env/config.yaml
  GODEBUG: x509ignoreCN=0