project: kicksware
component: references
nameOverride: references-service
fullnameOverride: references-service

replicaCount: 1
image:
  registry: registry.kicksware.com
  repository: api/references-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: api.kicksware.com
      paths:
        - /references
      middlewares: []
      services:
        - name: references-service
          port: 8080
          scheme: http

volumes: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  authKeys: auth-keys
  grpcTLSKeys: grpc-tls

config:
  environment: PROD
  configMountPath: /env

environment:
  name: k8s
  configPath: /env/config.yaml