apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  vanity.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
