project: kicksware
component: references
nameOverride: references-service
fullnameOverride: references-service

replicaCount: 2
image:
  registry: timothydockid
  repository: kicksware-reference-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
    secretName: grpc-tls
  routes:
    - host: api.kicksware.com
      paths:
        - /references
      middlewares: []
      services:
        - name: references-service
          port: 8080
          scheme: http
    - host: api.kicksware.com
      paths:
        - /health/references
      middlewares:
        - name: health-stripprefix
          namespace: infra
      services:
        - name: references-service
          port: 8080
          scheme: http
    - host: rpc.kicksware.com
      grpc: true
      paths:
        - /proto.ReferenceService
      entrypoints:
        - web
        - websecure
      services:
        - name: references-service
          port: 8080
          scheme: h2c

volumes: {}

resources:
  requests:
    cpu: 50m
    memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilization: 200

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  mounts:
    - name: auth-keys
      mountPath: /root/keys/auth
    - name: grpc-tls
      mountPath: /root/certs/grpc

config:
  environment: PROD
  configMountPath: /root/env

environment:
  ENV: k8s
  CONFIG_PATH: env/config.yaml
  GODEBUG: x509ignoreCN=0
  ELASTIC_APM_SERVICE_NAME: apm-server
  ELASTIC_APM_SERVER_URL: http://apm.kicksware.com:80
