version: '3.3'
services:
  traefik:
    container_name: traefik
    image:  traefik:v2.0
    restart: always
    command:
      - --log.level=DEBUG
      - --api=true
      - --api.insecure
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.file=true
      - --providers.file.filename=/proxy-config.toml
      - --providers.file.watch=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesResolvers.le.acme.email=timothy@kicksware.com
      - --certificatesResolvers.le.acme.storage=/proxy-service/acme.json
      - --certificatesResolvers.le.acme.tlschallenge=true
    labels:
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`monitor.kicksware.com`)
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`monitor.kicksware.com`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.domains[0].main=kicksware.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.kicksware.com
      - traefik.http.routers.traefik-secure.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect, add-dashboard
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.add-dashboard.addprefix.prefix=/dashboard/#/
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik-secure.tls.certresolver=le
      - traefik.http.routers.traefik-secure.middlewares=traefik-auth, add-dashboard
      - traefik.http.middlewares.traefik-auth.basicauth.users=root:$$apr1$$hnXmcCx0$$hTmrK2ZX5sKWiqE9IR6E6/
      - traefik.docker.network=web
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy-service:/proxy-service
      - type: bind
        source: /${SOURCE_DIR}/proxy-config.toml
        target: /proxy-config.toml
 

networks:
  web:
    external: true
