[http.routers]
  [http.routers.gitlab-ci]
    rule = "Host(`ci.kicksware.com`) && PathPrefix(`/`)"
    entrypoints = ["websecure"]
    service = "gitlab-ci"
  [http.routers.gitlab-ci.tls]
    certResolver = "le"

[http.services]
  [http.services.gitlab-ci.loadBalancer]
      [[http.services.gitlab-ci.loadBalancer.servers]]
        url = "https://ci.kicksware.com:44321"
