[http.routers]
  [http.routers.gitlab-ci]
    rule = "Host(`ci.kicksware.com`)"
    entrypoints = ["web-secure"]
    service = "gitlab-ci"
  [http.routers.gitlab-ci.tls]
    certResolver = "le"

[http.services]
  [http.services.gitlab-ci.loadBalancer]
      [[http.services.gitlab-ci.loadBalancer.servers]]
        address = "http://0.0.0.0:88"
