{{- if .Values.config.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |-
      {{ .Files.Get (include "chart.configPath" .) | indent 6 }}
{{- end }}
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.env
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.environment.name }}
  CONFIG_PATH: {{ .Values.environment.configPath }}