{{- range .Values.volumes }}
  {{- with .persistent }}
    {{- if and (.storageClass) (not .exists) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .claim }}
spec:
  storageClassName: {{ .storageClass }}
  volumeName: {{ .volumeName }}
  accessModes:
  {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
---
    {{- end }}
  {{- end }}
{{- end }}