project: kicksware
component: cdn
nameOverride: cdn-service
fullnameOverride: cdn-service

replicaCount: 1
image:
  registry: timothydockid
  repository: kicksware-cdn-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
    secretName: grpc-tls
  routes:
    - host: cdn.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: cdn-service
          port: 8080
          scheme: http
    - host: cdn.kicksware.com
      grpc: true
      paths:
        - /proto.ContentService
      entrypoints:
        - web
        - websecure
      services:
        - name: cdn-service
          port: 8080
          scheme: h2c

volumes:
  - name: storage
    persistent:
      claim: webapp-storage
      exists: true
    mountPath: /root/storage

resources:
  requests:
    cpu: 50m
    memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilization: 200

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  mounts:
    - name: auth-keys
      mountPath: /root/keys/auth
    - name: grpc-tls
      mountPath: /root/certs/grpc

config:
  environment: k8s
  configMountPath: /root/env

environment:
  ENV: k8s
  CONFIG_PATH: env/config.yaml
  GODEBUG: x509ignoreCN=0
  ELASTIC_APM_SERVICE_NAME: apm-server
  ELASTIC_APM_SERVER_URL: http://apm.kicksware.com:80
