[http.routers]
  [http.routers.gitlab-ci]
    rule = "Host(`ci.kicksware.com`)"  
    entrypoints = ["websecure"]
    service = "gitlab-ci"
  [http.routers.gitlab-ci.tls]
    certResolver = "le"
  [http.routers.sonarqube]
    rule = "Host(`test.kicksware.com`)"  
    entrypoints = ["websecure"]
    service = "sonarqube"
  [http.routers.sonarqube.tls]
    certResolver = "le"

[http.services]
  [http.services.gitlab-ci.loadBalancer]
      [[http.services.gitlab-ci.loadBalancer.servers]]
        url = "https://ci.kicksware.com:44321"
        # /var/opt/gitlab/nginx/conf/gitlab-http.conf --> server { listen *:88 }
  [http.services.sonarqube.loadBalancer]
      [[http.services.sonarqube.loadBalancer.servers]]
        url = "http:/0.0.0.0:9000"
