logLevel: DEBUG
defaultEntryPoints:
  - web
  - websecure
  - grpc

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    watch: true
    exposedByDefault: true #todo false
  file:
    watch: true
    directory: dynamic-config

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: timothy@kicksware.com
      storage: /cert/acme.json
      dnsChallenge:
        provider : digitalocean

serversTransport:
  rootCAs:
    - /keys/server.crt