---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- if .Values.config.configFile }}
      {{ .Values.config.configFile | nindent 6}}
    {{- else }}
      {{ .Files.Get (include "chart.configPath" .) | indent 6 }}
    {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.env
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.environment.name }}
  CONFIG_PATH: {{ .Values.environment.configPath }}