commonConfig:
  host: 0.0.0.0:8080
  hostname: cdn.kicksware.com
  usedDB: disk
  contentType: application/json
  apiEndpointFormat: https://api.kicksware.com/%s
  rpcEndpointFormat: rpc.kicksware.com:443
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
  accessKey: $AUTH_ACCESS_KEY
filesConfig:
  URL: /storage
mongoConfig:
  URL: mongodb://db.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: fs
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379