commonConfig:
  host: 0.0.0.0:8080
  hostname: cdn.kicksware.com
  usedDB: disk
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
authConfig:
  publicKeyPath: keys/public.key.pub
filesConfig:
  URL: /storage
mongoConfig:
  URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@db.kicksware.com
  database: sneakerResaleDB
  collection: orders
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379