commonConfig:
  host: localhost:8080
  hostname: cdn.kicksware.com
  usedDB: disk
  contentType: application/json
  apiEndpointFormat: https://api.kicksware.com/%s/
  rpcEndpointFormat: rpc.kicksware.com:443
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: ../keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: /source/certs/grpc/tls.crt
filesConfig:
  URL: /source/storage
mongoConfig:
  URL: mongodb://localhost:27017
  database: sneakerResaleDB
  collection: fs
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://localhost:6379
