commonConfig:
  host: 0.0.0.0:8080
  hostname: cdn.kicksware.com
  usedDB: files
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
authConfig:
  publicKeyPath: ../key/public.key.pub
filesConfig:
  URL: /source/storage
mongoConfig:
  URL: mongodb://root:greenJordans@mongodb:27017
  database: sneakerResaleDB
  collection: orders
  login: root
  password: greenJordans
  timeout: 30
redisConfig:
  URL: redis://redis:6379