version: '3.7'
services:
  products-service:
    build:
      context: ./product-service
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file: ./product-service/env/.env.prod
    hostname: kicksware.com
    image: products-service
    restart: always
    labels:
      - traefik.http.routers.product-service.rule=Host(`api.kicksware.com`) && PathPrefix(`/api/products`)
      - traefik.http.routers.product-service.tls=true
      - traefik.http.routers.product-service.tls.certresolver=le
      - traefik.docker.network=web
    networks:
      - web
      - data
    volumes:
      - /builds/root/kicksware-platform/middleware-service/product-service/env:/dist/env
      - key-source:/key
    links:
      - mongodb
    depends_on:
      - mongodb

  users-service:
    build:
      context: ./user-service
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file: ./user-service/env/.env.prod
    hostname: kicksware.com
    image: users-service
    restart: always
    labels:
      - traefik.http.routers.user-service.rule=Host(`api.kicksware.com`) && PathPrefix(`/api/users`) || PathPrefix(`/api/auth`) ||
        PathPrefix(`/api/mail`) || PathPrefix(`/api/interact`)
      - traefik.http.routers.user-service.tls=true
      - traefik.http.routers.user-service.tls.certresolver=le
      - traefik.docker.network=web
    networks:
      - web
      - data
    volumes:
      - /builds/root/kicksware-platform/middleware-service/user-service/env:/dist/env
      - key-source:/dist/key
      - /user-service/template:/dist/template
      - key-source:/key
    links:
      - mongodb
    depends_on:
      - mongodb

  references-service:
    build:
      context: ./reference-service
      dockerfile: ./docker/Dockerfile
      target: dev
    env_file: ./reference-service/env/.env.prod
    image: references-service
    restart: always
    labels:
      - traefik.http.routers.reference-service.rule=Host(`api.kicksware.com`) && PathPrefix(`/api/references`)
      - traefik.http.routers.reference-service.tls=true
      - traefik.http.routers.reference-service.tls.certresolver=le
      - traefik.docker.network=web
    volumes:
      - type: bind
        source: /builds/root/kicksware-platform/middleware-service/reference-service/env/config.prod.yaml
        target: /dist/env/config.prod.yaml
      - key-source:/key
    networks:
      - web
      - data
    links:
      - mongodb
    depends_on:
      - mongodb


  search-service:
    build:
      context: ./search-service
      dockerfile: ./docker/Dockerfile
      target: dev
    image: search-service
    restart: always
    env_file: ./search-service/env/.env.prod
    labels:
      - traefik.http.routers.search-service.rule=Host(`api.kicksware.com`) && PathPrefix(`/api/search`)
      - traefik.http.routers.search-service.tls=true
      - traefik.http.routers.search-service.tls.certresolver=le
      - traefik.docker.network=web
    networks:
      - web
      - elastic
      - data
    volumes:
      - type: bind
        source: /builds/root/kicksware-platform/middleware-service/search-service/env
        target: /dist/env
      - key-source:/key
    links:
      - references-service
      - products-service
      - elasticsearch
      - kibana
    depends_on:
      - references-service
      - products-service
      - elasticsearch
      - kibana


  mongodb:
    image: mongo:3.6.17
    restart: always
    ports:
      - 27017:27017
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=sneakerResaleDB
    networks:
      - data
    logging:
      driver: none

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic
    logging:
      driver: none

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic
    logging:
      driver: none

networks:
  elastic:
    driver: bridge
  data:
    driver: bridge
  web:
    external: true

volumes:
  key-source:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /source/keys
  elasticsearch-data:
