replicas: 1

volumeClaimTemplate:
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

esConfig:
  elasticsearch.yml: |
    cluster.name: timothy-elasticsearch
    network.host: 0.0.0.0
    ingest.geoip.downloader.enabled: false
