project: kicksware
component: cdn
nameOverride: cdn-service
fullnameOverride: cdn-service

replicaCount: 1
image:
  registry: registry.kicksware.com
  repository: api/cdn-service
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
    secretName: grpc-tls
  routes:
    - host: cdn.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: cdn-service
          port: 8080
          scheme: http
    - host: cdn.kicksware.com
      grpc: true
      paths:
        - /proto.ContentService
      entrypoints:
        - web
        - websecure
      services:
        - name: cdn-service
          port: 8080
          scheme: h2c

volumes:
  - name: storage
    persistent:
      claim: shared-storage-api
      volumeName: shared-storage-api
      exists: true
      storageClass: glusterfs
      size: 25Gi
      accessModes:
        - ReadWriteMany
    mountPath: /root/storage

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilization: 25

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  mounts:
    - name: auth-keys
      mountPath: /root/keys/auth
    - name: grpc-tls
      mountPath: /root/certs/grpc
    - name: mongo-tls
      mountPath: /root/certs/mongo

config:
  environment: PROD
  configMountPath: /root/env

environment:
  ENV: k8s
  CONFIG_PATH: env/config.yaml
  GODEBUG: x509ignoreCN=0
  ELASTIC_APM_SERVICE_NAME: apm-server
  ELASTIC_APM_SERVER_URL: http://apm.kicksware.com:80
