// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/beta.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Beta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueID string `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	Feature  string `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"`
	Done     bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *Beta) Reset() {
	*x = Beta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_beta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beta) ProtoMessage() {}

func (x *Beta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beta.ProtoReflect.Descriptor instead.
func (*Beta) Descriptor() ([]byte, []int) {
	return file_proto_beta_proto_rawDescGZIP(), []int{0}
}

func (x *Beta) GetUniqueID() string {
	if x != nil {
		return x.UniqueID
	}
	return ""
}

func (x *Beta) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *Beta) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type BetaFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetaID        []string          `protobuf:"bytes,1,rep,name=BetaID,proto3" json:"BetaID,omitempty"`
	RequestQuery  map[string]string `protobuf:"bytes,2,rep,name=RequestQuery,proto3" json:"RequestQuery,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RequestParams *RequestParams    `protobuf:"bytes,3,opt,name=RequestParams,proto3" json:"RequestParams,omitempty"`
}

func (x *BetaFilter) Reset() {
	*x = BetaFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_beta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetaFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetaFilter) ProtoMessage() {}

func (x *BetaFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetaFilter.ProtoReflect.Descriptor instead.
func (*BetaFilter) Descriptor() ([]byte, []int) {
	return file_proto_beta_proto_rawDescGZIP(), []int{1}
}

func (x *BetaFilter) GetBetaID() []string {
	if x != nil {
		return x.BetaID
	}
	return nil
}

func (x *BetaFilter) GetRequestQuery() map[string]string {
	if x != nil {
		return x.RequestQuery
	}
	return nil
}

func (x *BetaFilter) GetRequestParams() *RequestParams {
	if x != nil {
		return x.RequestParams
	}
	return nil
}

type BetaInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Betas         []*Beta        `protobuf:"bytes,1,rep,name=Betas,proto3" json:"Betas,omitempty"`
	RequestParams *RequestParams `protobuf:"bytes,2,opt,name=RequestParams,proto3" json:"RequestParams,omitempty"`
}

func (x *BetaInput) Reset() {
	*x = BetaInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_beta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetaInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetaInput) ProtoMessage() {}

func (x *BetaInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetaInput.ProtoReflect.Descriptor instead.
func (*BetaInput) Descriptor() ([]byte, []int) {
	return file_proto_beta_proto_rawDescGZIP(), []int{2}
}

func (x *BetaInput) GetBetas() []*Beta {
	if x != nil {
		return x.Betas
	}
	return nil
}

func (x *BetaInput) GetRequestParams() *RequestParams {
	if x != nil {
		return x.RequestParams
	}
	return nil
}

type BetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Betas []*Beta `protobuf:"bytes,1,rep,name=Betas,proto3" json:"Betas,omitempty"`
	Count int64   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *BetaResponse) Reset() {
	*x = BetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_beta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetaResponse) ProtoMessage() {}

func (x *BetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetaResponse.ProtoReflect.Descriptor instead.
func (*BetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_beta_proto_rawDescGZIP(), []int{3}
}

func (x *BetaResponse) GetBetas() []*Beta {
	if x != nil {
		return x.Betas
	}
	return nil
}

func (x *BetaResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RequestParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit         int32  `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int32  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	SortBy        string `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	SortDirection string `protobuf:"bytes,4,opt,name=SortDirection,proto3" json:"SortDirection,omitempty"`
}

func (x *RequestParams) Reset() {
	*x = RequestParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_beta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestParams) ProtoMessage() {}

func (x *RequestParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestParams.ProtoReflect.Descriptor instead.
func (*RequestParams) Descriptor() ([]byte, []int) {
	return file_proto_beta_proto_rawDescGZIP(), []int{4}
}

func (x *RequestParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RequestParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RequestParams) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *RequestParams) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

var File_proto_beta_proto protoreflect.FileDescriptor

var file_proto_beta_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x04, 0x42, 0x65, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0xea, 0x01, 0x0a, 0x0a,
	0x42, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x65,
	0x74, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x42, 0x65, 0x74, 0x61,
	0x49, 0x44, 0x12, 0x47, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6a, 0x0a, 0x09, 0x42, 0x65, 0x74, 0x61,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x42, 0x65, 0x74, 0x61, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74,
	0x61, 0x52, 0x05, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x22, 0x47, 0x0a, 0x0c, 0x42, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x42, 0x65, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61,
	0x52, 0x05, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7b, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f,
	0x72, 0x74, 0x42, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x6f, 0x72,
	0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xe6, 0x01, 0x0a, 0x0b, 0x42,
	0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x42,
	0x65, 0x74, 0x61, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74,
	0x61, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a,
	0x09, 0x45, 0x64, 0x69, 0x74, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_beta_proto_rawDescOnce sync.Once
	file_proto_beta_proto_rawDescData = file_proto_beta_proto_rawDesc
)

func file_proto_beta_proto_rawDescGZIP() []byte {
	file_proto_beta_proto_rawDescOnce.Do(func() {
		file_proto_beta_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_beta_proto_rawDescData)
	})
	return file_proto_beta_proto_rawDescData
}

var file_proto_beta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_beta_proto_goTypes = []interface{}{
	(*Beta)(nil),          // 0: proto.Beta
	(*BetaFilter)(nil),    // 1: proto.BetaFilter
	(*BetaInput)(nil),     // 2: proto.BetaInput
	(*BetaResponse)(nil),  // 3: proto.BetaResponse
	(*RequestParams)(nil), // 4: proto.RequestParams
	nil,                   // 5: proto.BetaFilter.RequestQueryEntry
}
var file_proto_beta_proto_depIdxs = []int32{
	5, // 0: proto.BetaFilter.RequestQuery:type_name -> proto.BetaFilter.RequestQueryEntry
	4, // 1: proto.BetaFilter.RequestParams:type_name -> proto.RequestParams
	0, // 2: proto.BetaInput.Betas:type_name -> proto.Beta
	4, // 3: proto.BetaInput.RequestParams:type_name -> proto.RequestParams
	0, // 4: proto.BetaResponse.Betas:type_name -> proto.Beta
	1, // 5: proto.BetaService.GetBetas:input_type -> proto.BetaFilter
	1, // 6: proto.BetaService.CountBetas:input_type -> proto.BetaFilter
	2, // 7: proto.BetaService.AddBetas:input_type -> proto.BetaInput
	2, // 8: proto.BetaService.EditBetas:input_type -> proto.BetaInput
	3, // 9: proto.BetaService.GetBetas:output_type -> proto.BetaResponse
	3, // 10: proto.BetaService.CountBetas:output_type -> proto.BetaResponse
	3, // 11: proto.BetaService.AddBetas:output_type -> proto.BetaResponse
	3, // 12: proto.BetaService.EditBetas:output_type -> proto.BetaResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_beta_proto_init() }
func file_proto_beta_proto_init() {
	if File_proto_beta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_beta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_beta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetaFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_beta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetaInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_beta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_beta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_beta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_beta_proto_goTypes,
		DependencyIndexes: file_proto_beta_proto_depIdxs,
		MessageInfos:      file_proto_beta_proto_msgTypes,
	}.Build()
	File_proto_beta_proto = out.File
	file_proto_beta_proto_rawDesc = nil
	file_proto_beta_proto_goTypes = nil
	file_proto_beta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BetaServiceClient is the client API for BetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BetaServiceClient interface {
	GetBetas(ctx context.Context, in *BetaFilter, opts ...grpc.CallOption) (*BetaResponse, error)
	CountBetas(ctx context.Context, in *BetaFilter, opts ...grpc.CallOption) (*BetaResponse, error)
	AddBetas(ctx context.Context, in *BetaInput, opts ...grpc.CallOption) (*BetaResponse, error)
	EditBetas(ctx context.Context, in *BetaInput, opts ...grpc.CallOption) (*BetaResponse, error)
}

type betaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBetaServiceClient(cc grpc.ClientConnInterface) BetaServiceClient {
	return &betaServiceClient{cc}
}

func (c *betaServiceClient) GetBetas(ctx context.Context, in *BetaFilter, opts ...grpc.CallOption) (*BetaResponse, error) {
	out := new(BetaResponse)
	err := c.cc.Invoke(ctx, "/proto.BetaService/GetBetas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betaServiceClient) CountBetas(ctx context.Context, in *BetaFilter, opts ...grpc.CallOption) (*BetaResponse, error) {
	out := new(BetaResponse)
	err := c.cc.Invoke(ctx, "/proto.BetaService/CountBetas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betaServiceClient) AddBetas(ctx context.Context, in *BetaInput, opts ...grpc.CallOption) (*BetaResponse, error) {
	out := new(BetaResponse)
	err := c.cc.Invoke(ctx, "/proto.BetaService/AddBetas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betaServiceClient) EditBetas(ctx context.Context, in *BetaInput, opts ...grpc.CallOption) (*BetaResponse, error) {
	out := new(BetaResponse)
	err := c.cc.Invoke(ctx, "/proto.BetaService/EditBetas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BetaServiceServer is the server API for BetaService service.
type BetaServiceServer interface {
	GetBetas(context.Context, *BetaFilter) (*BetaResponse, error)
	CountBetas(context.Context, *BetaFilter) (*BetaResponse, error)
	AddBetas(context.Context, *BetaInput) (*BetaResponse, error)
	EditBetas(context.Context, *BetaInput) (*BetaResponse, error)
}

// UnimplementedBetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBetaServiceServer struct {
}

func (*UnimplementedBetaServiceServer) GetBetas(context.Context, *BetaFilter) (*BetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBetas not implemented")
}
func (*UnimplementedBetaServiceServer) CountBetas(context.Context, *BetaFilter) (*BetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountBetas not implemented")
}
func (*UnimplementedBetaServiceServer) AddBetas(context.Context, *BetaInput) (*BetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBetas not implemented")
}
func (*UnimplementedBetaServiceServer) EditBetas(context.Context, *BetaInput) (*BetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBetas not implemented")
}

func RegisterBetaServiceServer(s *grpc.Server, srv BetaServiceServer) {
	s.RegisterService(&_BetaService_serviceDesc, srv)
}

func _BetaService_GetBetas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetaFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetaServiceServer).GetBetas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BetaService/GetBetas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetaServiceServer).GetBetas(ctx, req.(*BetaFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BetaService_CountBetas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetaFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetaServiceServer).CountBetas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BetaService/CountBetas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetaServiceServer).CountBetas(ctx, req.(*BetaFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BetaService_AddBetas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetaInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetaServiceServer).AddBetas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BetaService/AddBetas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetaServiceServer).AddBetas(ctx, req.(*BetaInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BetaService_EditBetas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetaInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetaServiceServer).EditBetas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BetaService/EditBetas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetaServiceServer).EditBetas(ctx, req.(*BetaInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _BetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BetaService",
	HandlerType: (*BetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBetas",
			Handler:    _BetaService_GetBetas_Handler,
		},
		{
			MethodName: "CountBetas",
			Handler:    _BetaService_CountBetas_Handler,
		},
		{
			MethodName: "AddBetas",
			Handler:    _BetaService_AddBetas_Handler,
		},
		{
			MethodName: "EditBetas",
			Handler:    _BetaService_EditBetas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/beta.proto",
}
