commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
securityConfig:
  tlsCertificate:
    enableTLS: true
    certFile: ../key/server.crt
    keyFile: ../key/server.key
authConfig:
  publicKeyPath: ../key/public.key.pub
mongoConfig:
  URL: mongodb://root:greenJordans@mongodb:27017
  database: sneakerResaleDB
  collection: references
  login: admin
  password: admin
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://postgres:1879@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: References
  login: postgres
  password: 1879
  timeout: 30
