commonConfig:
  host: localhost:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
authConfig:
  publicKeyPath: ../key/public.key.pub
mongoConfig:
  URL: mongodb://localhost:27017
  database: sneakerResaleDB
  collection: references
  login: admin
  password: admin
  timeout: 30
redisConfig:
  URL: redis://localhost:6379
postgresConfig:
  URL: postgres://postgres:1879@localhost:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: References
  login: postgres
  password: 1879
  timeout: 30
