version: '3.3'
services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: web-app
    restart: always
    env_file: ./env/.env
    labels:
      - traefik.http.routers.web-app.rule=Host(`kicksware.com`)
      - traefik.http.routers.web-app.tls=true
      - traefik.http.routers.web-app.tls.certresolver=le
      - traefik.docker.network=sneaker-resale-platform_web
    networks:
      - web

networks:
  web:
    external: true
