version: '3.3'
services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: web-app
    restart: always
    env_file: ./env/.env
    labels:
      - traefik.http.routers.web-app.rule=Host(`kicksware.com`)
      - traefik.http.routers.web-app.tls=true
      - traefik.http.routers.web-app.tls.certresolver=le
      - traefik.docker.network=web
    networks:
      - web
    volumes:
      - type: bind
        source: /source/storage
        target: /source/storage
      - type: bind
        source: /source/keys
        target: /source/keys

networks:
  web:
    external: true
