project: kicksware
component: proxy
nameOverride: ""
fullnameOverride: ""
sourceDir: &sourceDir /run/desktop/mnt/host/wsl/source/repos/kicksware-platform

replicaCount: 1
image:
  repository: traefik
  pullPolicy: IfNotPresent
  tag: v2.2

service:
  type: LoadBalancer
  port: 80
  securePort: 443
  adminPort: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  routes:
    - host: monitor.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: api@internal
          kind: TraefikService
          port: 8080
          scheme: http
  tls:
    enabled: true
    certResolver: le
    domains:
      - main: kicksware.com
        sans:
          - '*.kicksware.com'

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG
  accesslog: true

volumes:
  - name: cert
    hostPathBase: /run/desktop/mnt/host/wsl
    hostPath: /source/cert
    mountPath: /cert
    type: Directory
  - name: keys
    hostPathBase: /run/desktop/mnt/host/wsl
    hostPath: /source/keys
    mountPath: /keys
    type: Directory
  - name: dynamic
    hostPathBase: *sourceDir
    hostPath: /proxy-service/dynamic-config
    mountPath: &dynamic-mount /dynamic-config
    type: Directory

providers:
  file:
    enabled: true
    directory: *dynamic-mount
    watch: true
  kubernetescrd:
    enabled: true
  kubernetesingress:
    enabled: true

acme:
  enabled: true
  email: timothy@kicksware.com
  storage: /cert/acme.json
  dnsChallenge:
    enabled: true
    provider: digitalocean
    envName: DO_AUTH_TOKEN
    token: 6229b9e18dd51158da31da743bcf36262a11e8075a8ea2847d555cb9a3e47bf4

serverTransport:
  rootCAs:
    - /keys/server.crt
  insecureSkipVerify: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""