commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://api.kicksware.com/%s/
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
mongoConfig:
  URL: mongodb://db.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: references
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: References
  login: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  timeout: 30
