commonConfig:
  host: 0.0.0.0:8080
  hostname: api.kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
authConfig:
  publicKeyPath: keys/public.key.pub
mongoConfig:
  URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@db.kicksware.com
  tlsKey: certs/mongo/tls.key
  tlsCert: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: orders
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Orders
  login: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  timeout: 30
