commonConfig:
  host: localhost:8080
  hostname: api.kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: rpc.kicksware.com:443
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: ../key/public.key.pub
  tlsCertificate:
    enableTLS: true
    certFile: ../keys/server.crt
mongoConfig:
  URL: mongodb://localhost:27017
  database: sneakerResaleDB
  collection: orders
  timeout: 30
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
redisConfig:
  URL: redis://localhost:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Orders
  timeout: 30
