commonConfig:
  host: 0.0.0.0:8080
  hostname: api.kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: rpc.kicksware.com:443
authConfig:
  publicKeyPath: keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
mongoConfig:
  URL: mongodb://db.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: orders
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Orders
  login: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  timeout: 30
