commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
securityConfig:
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
    keyFile: certs/grpc/tls.key
authConfig:
  publicKeyPath: keys/public.key.pub
mongoConfig:
  URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@db.kicksware.com
  TLS:
    enableTLS: true
    certFile: certs/mongo/tls.key
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: products
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 45
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Products
  login: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  timeout: 45
