commonConfig:
  host: localhost:8080
  hostname: kicksware.com
  contentType: application/json
  innerServiceFormat: rpc.kicksware.com:443
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: ../keys/public.key.pub
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: ../keys/server.crt
elasticConfig:
  URL: https://search.kicksware.com:443
  index: sneaker_reference
  startupDelay: 60
  sniffing: false
searchConfig:
  type: phrase_prefix
  slop: 3
  fields:
    - ManufactureSku^5
    - ModelName^4
    - BrandName^2
    - Nickname^2
    - Description
    - Color
