commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  contentType: application/json
  apiEndpointFormat: https://api.kicksware.com/%s/
  rpcEndpointFormat: rpc.kicksware.com:443
securityConfig:
  tlsCertificate:
    enableTLS: false
authConfig:
  publicKeyPath: keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
elasticConfig:
  URL: https://search.kicksware.com:443
  index: sneaker_reference
  startupDelay: 100
  sniffing: false
searchConfig:
  type: phrase_prefix
  slop: 3
  fields:
    - ManufactureSku^5
    - ModelName^4
    - BrandName^2
    - Nickname^2
    - Description
    - Color
