project: kicksware
component: search
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
image:
  repository: search-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  provider: traefik.containo.us/v1alpha1
  entrypoints:
    - web
    - websecure
  routes:
    - host: api.kicksware.com
      paths:
        - /search
      middlewares: []
      services:
        - name: user-service
          port: 8080
          scheme: http

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

config:
  enviroment: PROD
  host: 0.0.0.0:8080
  hostname: api.kicksware.com
  configPath: /env/config.prod.yaml