commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
securityConfig:
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
    keyFile: certs/grpc/tls.key
authConfig:
  issuerName: middleware/user-service
  tokenExpirationDelta: 360
  privateKeyPath: keys/auth/private.key
  publicKeyPath: keys/auth/public.key
mailConfig:
  server: $MAIL_SERVER
  address: $MAIL_ADDRESS
  password: $MAIL_PASSWORD
  verifyEmailTemplate: template/verify.template.html
  resetPasswordTemplate: template/reset.template.html
  notificationTemplate: template/notification.template.html
fallbackMailConfig:
  server: $FALLBACK_MAIL_SERVER
  address: $FALLBACK_MAIL_ADDRESS
  password: $FALLBACK_MAIL_PASSWORD
  verifyEmailTemplate: template/verify.template.html
  resetPasswordTemplate: template/reset.template.html
  notificationTemplate: template/notification.template.html
mongoConfig:
  URL: mongodb://db.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: users
  likesCollection: likes
  remoteCollection: remotes
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Users
  likesCollection: Likes
  login: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  timeout: 30
