commonConfig:
  host: 0.0.0.0:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
authConfig:
  issuerName: middleware/user-service
  tokenExpirationDelta: 72
  privateKeyPath: key/private.key
  publicKeyPath: ../key/public.key.pub
mailConfig:
  server: smtp.zoho.eu:465
  address: accounts@kicksware.com
  password: Er2PQRQc
  verifyEmailTemplate: template/verify.template.html
  resetPasswordTemplate: template/verify.template.html
  notificationTemplate: template/verify.template.html
mongoConfig:
  URL: mongodb://mongodb:27017
  database: sneakerResaleDB
  collection: users
  login: admin
  password: admin
  timeout: 30
redisConfig:
  URL: redis://redis:6379
postgresConfig:
  URL: postgres://postgres:1879@postgres:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Users
  login: postgres
  password: 1879
  timeout: 30
