commonConfig:
  host: localhost:8080
  hostname: kicksware.com
  usedDB: mongo
  contentType: application/json
  innerServiceFormat: http://%s:8080/%s/
securityConfig:
  tlsCertificate:
    enableTLS: true
    caCertFile: ../key/ca-cert.pem
    certFile: ../key/server-cert.pem
    keyFile: ../key/server-key.pem
authConfig:
  issuerName: middleware/user-service
  tokenExpirationDelta: 18
  privateKeyPath: key/private.key
  publicKeyPath: ../key/public.key.pub
mailConfig:
  server: smtp.zoho.eu:465
  address: accounts@kicksware.com
  password: Er2PQRQc
  verifyEmailTemplate: template/verify.template.html
  resetPasswordTemplate: template/reset.template.html
  notificationTemplate: template/notification.template.html
fallbackMailConfig:
  server: smtp.gmail.com:465
  address: users.kicksware@gmail.com
  password: Er2PQRQc
  verifyEmailTemplate: template/verify.template.html
  resetPasswordTemplate: template/reset.template.html
  notificationTemplate: template/notification.template.html
mongoConfig:
  URL: mongodb://localhost:27017
  database: sneakerResaleDB
  collection: users
  likesCollection: likes
  remoteCollection: remotes
  login: admin
  password: admin
  timeout: 30
redisConfig:
  URL: redis://localhost:6379
postgresConfig:
  URL: postgres://postgres:1879@localhost:5432/sneakerResaleDB
  database: sneakerResaleDB
  collection: Users
  likesCollection: Likes
  login: postgres
  password: 1879
  timeout: 30
