project: kicksware
component: proxy
nameOverride: ""
fullnameOverride: ""
namespace: kube-system

replicaCount: 1
image:
  repository: traefik
  pullPolicy: IfNotPresent
  tag: v2.2

service:
  type: NodePort
  port: 80
  securePort: 443
  adminPort: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: users.local
      paths: []
  tls:
    enabled: false
    secrets:
      - secretName: chart-tls
        hosts: []

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG
  accesslog: true

providers:
  file:
    enabled: true
    directory: /dynamic-config
    watch: true
  kubernetescrd:
    enabled: true
  kubernetesingress:
    enabled: true

acme:
  enabled: true
  email: timothy@kicksware.com
  storage: /cert/acme.json
  dnsChallenge:
    enabled: true
    provider: digitalocean
    envName: DO_AUTH_TOKEN
    token: 6229b9e18dd51158da31da743bcf36262a11e8075a8ea2847d555cb9a3e47bf4

serverTransport:
  rootCAs:
    - /keys/server.crt
  insecureSkipVerify: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

config:
  enviroment: PROD
  host: 0.0.0.0:8080
  hostname: api.kicksware.com
  configPath: /env/config.prod.yaml