commonConfig:
  host: 0.0.0.0:8080
  hostname: api.kicksware.com
  contentType: application/json
  apiEndpointFormat: https://api.kicksware.com/%s
  rpcEndpointFormat: rpc.kicksware.com:443
eventBusConfig:
  endpoint: amqps://$RABBITMQ_USER:$RABBITMQ_PASSWORD@amqp.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/rabbitmq/ca.crt
authConfig:
  publicKeyPath: keys/auth/public.key
  authEndpoint: https://api.kicksware.com/auth/guest
  tlsCertificate:
    enableTLS: true
    certFile: certs/grpc/tls.crt
  accessKey: $AUTH_ACCESS_KEY
mongoConfig:
  URL: mongodb://db.kicksware.com:443
  TLS:
    enableTLS: true
    certFile: certs/mongo/ca.crt
    keyFile: certs/mongo/tls.key
  database: sneakerResaleDB
  collection: rates
  login: $MONGO_USER
  password: $MONGO_PASSWORD
  timeout: 30
