project: kicksware
component: users
nameOverride: users-service
fullnameOverride: users-service
replicaCount: 1

image:
  registry: registry.kicksware.com
  repository: api/users-service
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
    secretName: grpc-tls
  routes:
    - host: api.kicksware.com
      paths:
        - /users
        - /auth
        - /mail
        - /interact
      middlewares: []
      services:
        - name: users-service
          port: 8080
          scheme: http
    - host: api.kicksware.com
      paths:
        - /health/users
      middlewares:
        - name: health-stripprefix
          namespace: gateway
      services:
        - name: users-service
          port: 8080
          scheme: http
    - host: rpc.kicksware.com
      grpc: true
      paths:
        - /proto.UserService
        - /proto.AuthService
        - /proto.MailService
        - /proto.InteractService
      entrypoints:
        - web
        - websecure
      services:
        - name: users-service
          port: 8080
          scheme: h2c

volumes: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  mounts:
    - name: auth-keys
      mountPath: /root/keys/auth
    - name: grpc-tls
      mountPath: /root/certs/grpc
    - name: mongo-tls
      mountPath: /root/certs/mongo

config:
  environment: k8s
  configMountPath: /root/env

environment:
  name: k8s
  configPath: env/config.yaml
