commonConfig:
  host: localhost:8080
  hostname: kicksware.com
  contentType: application/json
  innerServiceFormat: api.kicksware.com
authConfig:
  publicKeyPath: ../key/public.key.pub
  authEndpoint: https://api.kicksware.com/auth/guest
elasticConfig:
  URL: http://localhost:9200
  index: sneaker_reference
  startupDelay: 60
  sniffing: false
searchConfig:
  type: phrase_prefix
  slop: 3
  fields:
    - ManufactureSku^5
    - ModelName^4
    - BrandName^2
    - Nickname^2
    - Description
    - Color
