project: kicksware
component: web-app
nameOverride: web-app
fullnameOverride: web-app
replicaCount: 1

image:
  repository: ci.kicksware.com:5050/root/kicksware-platform/web-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: web-app
          port: 8080
          scheme: http

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  grpcTLSKeys: grpc-tls

config:
  environment: PROD

environment:
  name: PROD